### ISSUE TITLE
Failed to resolve "volley-release"

### ISSUE THREAD

**Issue by FarhanAhmad** [Adyen/adyen-checkout-android#11]
Hi,

Sample app works, but adding adyenpaysdk as dependency gives following issue:

"Failed to resolve: :volley-release:"

**Comment by FarhanAhmad** [comment]
I added this now to fix this issue: compile 'com.android.volley:volley:1.0.0'

**Comment by lnicolet** [comment]
I'm actually getting the same issue. Where did you added 
    compile 'com.android.volley:volley:1.0.0' to fix this?
